version: 2.0
jobs:
  build:
    macos:
      xcode: 11.4.0
    environment:
      HOMEBREW_NO_AUTO_UPDATE: 1
    steps:
      - checkout
      - run: brew install packer
      - run: packer --version
      - run: brew cask install vagrant
      - run: vagrant --version
      - run: brew cask install virtualbox
      - run: VBoxManage --version
